"""Create event and timeslot tables

Revision ID: ba114bfc4f08
Revises: f6ac7ccc4302
Create Date: 2022-06-06 17:55:38.751907-07:00

"""
from alembic import op
import sqlalchemy as sa

from stv_services.data_store.model import epoch

# field type for timestamp with timezone
Timestamp = sa.TIMESTAMP(timezone=True)

# revision identifiers, used by Alembic.
revision = "ba114bfc4f08"
down_revision = "f6ac7ccc4302"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_info",
        sa.Column("uuid", sa.Integer, primary_key=True, nullable=False),
        sa.Column("created_date", Timestamp, index=True, nullable=False),
        sa.Column("modified_date", Timestamp, index=True, nullable=False),
        sa.Column("updated_date", Timestamp, index=True, default=epoch),
        sa.Column("title", sa.Text, nullable=False),
        sa.Column("description", sa.Text, default=""),
        sa.Column("sponsor_id", sa.Integer, index=True, nullable=False),
        sa.Column("partner_name", sa.Text, index=True, default=""),
        sa.Column("event_type", sa.Text, index=True, nullable=False),
        sa.Column("event_url", sa.Text, nullable=False),
        sa.Column("contact_email", sa.Text, index=True, default=""),
        sa.Column("contact_id", sa.Text, index=True, default=""),
        sa.Column("is_featured", sa.Boolean, index=True, default=False),
        sa.Column("featured_name", sa.Text, default=""),
        sa.Column("featured_description", sa.Text, default=""),
        sa.Column("feature_start", Timestamp, default=epoch),
        sa.Column("feature_end", Timestamp, default=epoch),
        sa.Column("is_event", sa.Boolean, index=True, default=False),
        sa.Column("event_record_id", sa.Text, index=True, default=""),
        sa.Column("event_updated", Timestamp, index=True, default=epoch),
    )
    op.create_table(
        "timeslot_info",
        sa.Column("uuid", sa.Integer, primary_key=True, nullable=False),
        sa.Column("start_date", Timestamp, index=True, nullable=False),
        sa.Column("end_date", Timestamp, index=True, nullable=False),
        sa.Column("event_id", sa.Integer, index=True, nullable=False),
    )


def downgrade():
    op.drop_table("timeslot_info")
    op.drop_table("event_info")
